yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path('new/', views.new_post, name='new_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path('<str:username>/<int:post_id>/edit/',
         views.post_edit, name='post_edit')
]

yatube/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path('about/', include('about.urls', namespace='about')),
    path("", include("posts.urls")),
    path('admin/my-admin/', admin.site.urls)
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts")
    group = models.ForeignKey(
        Group, on_delete=models.SET_NULL, related_name="posts",
        blank=True, null=True)

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['group', 'text']
        labels = {
            'group': ('Группа'),
            'text': ('Текст')
        }
        help_texts = {
            'group': ('Группа для этой записи'),
            'text': ('Текст этой записи')
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ("first_name", "last_name", "username", "email")

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Post, Group
from .forms import PostForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


User = get_user_model()


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')

    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        'page': page,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by("-pub_date")

    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        "group": group,
        "page": page
    }

    return render(request, "posts/group.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all().order_by("-pub_date")

    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        'page': page,
        'author': author,
        "posts_count": author.posts.count()
    }

    return render(request, 'posts/profile.html', context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, pk=post_id)

    context = {
        "post": post,
        "author": post.author,
        "posts_count": post.author.posts.count()
    }

    return render(request, "posts/post.html", context)


@login_required
def new_post(request):
    is_new = True
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("index")
    form = PostForm()

    context = {
        "form": form,
        "is_new": is_new,
    }

    return render(request, "posts/post_form.html", context)


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, pk=post_id)

    if request.user == post.author:
        form = PostForm(instance=post, data=request.POST or None)

        if form.is_valid():
            form.save()

            return redirect('post', username=username, post_id=post_id)

        context = {
            'form': form,
        }

        return render(request, 'posts/post_form.html', context)

    else:
        return redirect('post', username=username, post_id=post_id)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("signup")
    template_name = "signup.html"

yatube/about/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Об авторе
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Здесь вы немного узнаете о создателе сайта
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>
            	Меня зовут: <b>Лёва Нетреба</b><br>
				И являюсь создателям этого сайта<br>
			</p>
			<hr>
			<h4>Об авторе</h4>
			<p>Я молодой программист который прокладывает себе путь в <b>мир it</b>, я проходил 3 небольших курса в основном они были про <b>Python</b> и сейчас прохожу большие курсы по <b>Python</b> в <b>Яндекс.Практикум</b> и разрабатываю этот сайт. Я разрабатывал разные небольшие сайты и программы для себя. Я немного знаю языки <b>Python</b> и <b>JavaScript</b>.</p>
			<img src="" alt="">
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

yatube/about/templates/about/tech.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Технологии
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Здесь можно увидеть какие инструменты использовал автор для создания этого сайта
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <ul>
            	<li>Sublime Text</li>
            	<p>В этой программе я писал код</p>
            	<li>PyCharm CE</li>
            	<p>Здесь я писал более сложные коды</p>
            	<li>Slack</li>
            	<p>Тут я общался с другими программистами и получал помощь и советы</p>
            	<li>Github</li>
            	<p>И тут я выкладываю свой код сайта в интернет</p>
            </ul>
            	
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

yatube/posts/templates/posts/group.html
{% extends "base.html" %} 
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
	
	<p>{{ group.description }}</p>
	
	{% for post in page %}
		<h3>
			Автор: {{ post.author.get_full_name }}, дата публикации: {{ post.pub_date|date:"d M Y" }}
		</h3>
		<p>{{ post.text|linebreaksbr }}</p>
		<hr>
	{% endfor %}

	{% include "paginator.html" %}

{% endblock %}

yatube/posts/templates/posts/index.html
{% extends "base.html" %} 
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}

  	<h1>Последние обновления на сайте<h1>
    {% for post in page %}
    <h3>
        Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

    {% include "paginator.html" %}

{% endblock %}

yatube/posts/templates/posts/post.html
{% extends "base.html" %}
{% block title %}Запись {{ post.get_full_name }}{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <div class="h2">
            <!-- Имя автора -->
            {{ author.get_full_name }}
          </div>
          <div class="h3 text-muted">
            <!-- username автора -->
             @{{ author.username }}
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">
              Подписчиков: XXX <br />
              Подписан: XXX
            </div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">
              <!--Количество записей -->
              Записей: {{ posts_count }}
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-9">
    <!-- Пост -->
      <div class="card mb-3 mt-1 shadow-sm">
        <div class="card-body">
          <p class="card-text">
            <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
            <a href="/{{ author.username }}/">
              <strong class="d-block text-gray-dark">
                @{{ author.username }}
              </strong>
            </a>
            <!-- Текст поста -->
            {{ post.text }}
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
~~~~              <!-- Ссылка на редактирование, показывается только автору записи.
              Эту ссылку вы подключите в финальном задании спринта -->
              {% if user.username == author.username %}
                <a class="btn btn-sm text-muted" href="/{{ author.username }}/{{ post.id }}/edit" role="button">Редактировать</a>
              {% endif %}
            </div>
            <!-- Дата публикации  -->
            <small class="text-muted">31 июля 1854 г. 0:00</small>
          </div>
        </div>
      </div>
    </div>
  </div>
  </main>
{% endblock %}

yatube/posts/templates/posts/post_edit.html
{% extends "base.html" %} 
{% block title %}Редактировать запись{% endblock %}
{% block content %}
{% load user_filters %}
    <div class="row justify-content-center">
	  <div class="col-md-8 p-5">
	    <div class="card">
	      <div class="card-header">Редактировать запись</div>
	      <div class="card-body">

	      	{% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
	      	
	        <form method="post">
	          {% csrf_token %}

	          {% for field in form %}
	            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
	              <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
	              <div class="col-md-6">
	                {{ field|addclass:"form-control" }}
	                {% if field.help_text %}
	                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
	                {% endif %}
	              </div>
	            </div>
	          {% endfor %}

	          <div class="col-md-6 offset-md-4">              
	              <button type="submit" class="btn btn-primary">
	                Сохранить
	              </button>
	          </div>
	        </form>
	      </div> <!-- card body -->
	    </div> <!-- card -->
	  </div> <!-- col -->
	</div> <!-- row -->

{% endblock %}

yatube/posts/templates/posts/post_form.html
{% extends "base.html" %}
{% block title %}
{% if is_new %}
	Добавить запись
{% else %}
    Редактировать запись
{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
    <div class="row justify-content-center">
	  <div class="col-md-8 p-5">
	    <div class="card">
	      <div class="card-header">
	      	{% if is_new %}
	      		Добавить запись
	      	{% else %}
    			Редактировать запись
			{% endif %}
	      </div>
	      <div class="card-body">

	      	{% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
	      	
	        <form method="post">
	          {% csrf_token %}

	          {% for field in form %}
	            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
	              <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
	              <div class="col-md-6">
	                {{ field|addclass:"form-control" }}
	                {% if field.help_text %}
	                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
	                {% endif %}
	              </div>
	            </div>
	          {% endfor %}

	          <div class="col-md-6 offset-md-4">              
	              <button type="submit" class="btn btn-primary">
	                Сохранить
	              </button>
	          </div>
	        </form>
	      </div> <!-- card body -->
	    </div> <!-- card -->
	  </div> <!-- col -->
	</div> <!-- row -->

{% endblock %}

yatube/posts/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}{{ author.get_full_name }}{% endblock %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <div class="h2">
            <!-- Имя автора -->
            {{ author.get_full_name }}
          </div>
          <div class="h3 text-muted">
            <!-- username автора -->
            @{{ author.username }}
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">
              Подписчиков: XXX <br />
              Подписан: XXX
            </div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">
              <!-- Количество записей -->
              Записей: {{ posts_count }}
            </div>
          </li>
        </ul>
      </div>
    </div>

    <div class="col-md-9">
      {% for post in page %}                
      <!-- Начало блока с отдельным постом --> 
      <div class="card mb-3 mt-1 shadow-sm">
        <div class="card-body">
          <p class="card-text">
            <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
            <a href="/{{ author.username }}/"><strong class="d-block text-gray-dark">@{{ author.username }}</strong></a>
            <!-- Текст поста -->
            {{ post.text }}
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group ">
              <!-- Ссылка на страницу записи в атрибуте href-->
              <a class="btn btn-sm text-muted" href="/{{ author.username }}/{{ post.id }}/" role="button">Добавить комментарий</a>
              <!-- Ссылка на редактирование, показывается только автору записи -->
              {% if user.username == author.username %}
                <a class="btn btn-sm text-muted" href="/{{ author.username }}/{{ post.id }}/edit" role="button">Редактировать</a>
              {% endif %}
            </div>
            <!-- Дата публикации  -->
            <small class="text-muted">{{ post.pub_date }}</small>
          </div>
        </div>
      </div>
      <!-- Конец блока с отдельным постом -->
      {% endfor %}
      <!-- Остальные посты -->  
      <!-- Здесь постраничная навигация паджинатора -->
      {% include "paginator.html" %}
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/base.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'static/bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'static/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'static/bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            <h1>{% block header %}{% endblock %}</h1>

            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>
</html>

yatube/templates/footer.html
<!-- Шаблон footer.html -->
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        <a class="btn btn-primary" href="{% url 'new_post' %}">Новая запись</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

yatube/templates/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

                {% for error in form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}


                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}